language: java
jdk: oraclejdk8

# enable display
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

# skip the install step
install: true

script: mvn clean verify coveralls:report
